---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Shell Check

on:
  push:
    branches:
      - main
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

permissions: {}

concurrency:
  group: shellcheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run ShellCheck (errors only)
        run: |
          # Install shellcheck
          sudo apt-get update
          sudo apt-get install -y --no-upgrade shellcheck
          
          # Run shellcheck on all .sh files (only fail on errors, not warnings)
          find . -name "*.sh" -not -path "./.git/*" -print0 | xargs -0 shellcheck --severity=error --format=gcc

      - name: Run ShellCheck (show warnings)
        continue-on-error: true
        run: |
          # Show warnings for informational purposes
          echo "::group::ShellCheck Warnings (informational only)"
          find . -name "*.sh" -not -path "./.git/*" -print0 | xargs -0 shellcheck --severity=warning --format=gcc || true
          echo "::endgroup::"

